### ISSUE TITLE
Issue Starting GameServer

### ISSUE THREAD

**Issue by Dark98** [dodian-community/osrs-game-server#8]
I get the error below when trying to run with any revision of the 201 cache
Edit: Fixed by running GenerateNames Gradle Task
```
> Task :game-server:run
[INFO] Apr 22, 2022 3:43:03 AM: Starting up server - please wait... <- Server$startup$1::invokeSuspend()
[DEBUG] Apr 22, 2022 3:43:05 AM: Append module to builder (module=XteaModule) <- KotlinGameModule::unaryMinus()
[DEBUG] Apr 22, 2022 3:43:05 AM: Append module to builder (module=NamedTypeModule) <- KotlinGameModule::unaryMinus()
[DEBUG] Apr 22, 2022 3:43:05 AM: Append module to builder (module=TypeLoaderModule) <- KotlinGameModule::unaryMinus()
[DEBUG] Apr 22, 2022 3:43:05 AM: Append module to builder (module=NamedConfigFileModule) <- KotlinGameModule::unaryMinus()
[DEBUG] Apr 22, 2022 3:43:05 AM: Append module to builder (module=GameframeModule) <- KotlinGameModule::unaryMinus()
[DEBUG] Apr 22, 2022 3:43:05 AM: Append module to builder (module=LoginPacketModule) <- KotlinGameModule::unaryMinus()
[DEBUG] Apr 22, 2022 3:43:05 AM: Append module to builder (module=PacketStructureModule) <- KotlinGameModule::unaryMinus()
[DEBUG] Apr 22, 2022 3:43:05 AM: Append module to builder (module=DefaultSerializerModule) <- KotlinGameModule::unaryMinus()
[DEBUG] Apr 22, 2022 3:43:05 AM: Append module to builder (module=YamlSerializerModule) <- KotlinGameModule::unaryMinus()
[INFO] Apr 22, 2022 3:43:06 AM: Launching RS Mod <- Server$startup$1::invokeSuspend()
[DEBUG] Apr 22, 2022 3:43:07 AM: Register cache type loader (type=NpcTypeLoader) <- CacheTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:07 AM: Register cache type loader (type=ObjectTypeLoader) <- CacheTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:07 AM: Register cache type loader (type=ItemTypeLoader) <- CacheTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:07 AM: Register cache type loader (type=VarpTypeLoader) <- CacheTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:07 AM: Register cache type loader (type=VarbitTypeLoader) <- CacheTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:07 AM: Register cache type loader (type=ComponentTypeLoader) <- CacheTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:07 AM: Register cache type loader (type=EnumTypeLoader) <- CacheTypeLoaderList::register()
[INFO] Apr 22, 2022 3:43:07 AM: Loaded 3189 varp type files <- VarpTypeLoader::load()
[INFO] Apr 22, 2022 3:43:07 AM: Loaded 13118 varbit type files <- VarbitTypeLoader::load()
[INFO] Apr 22, 2022 3:43:07 AM: Loaded 4068 enum type files <- EnumTypeLoader::load()
[INFO] Apr 22, 2022 3:43:07 AM: Loaded 11254 npc type files <- NpcTypeLoader::load()
[INFO] Apr 22, 2022 3:43:07 AM: Loaded 42852 object type files <- ObjectTypeLoader::load()
[INFO] Apr 22, 2022 3:43:07 AM: Loaded 26266 item type files <- ItemTypeLoader::load()
[INFO] Apr 22, 2022 3:43:08 AM: Loaded 730 interface type files <- ComponentTypeLoader::load()
[DEBUG] Apr 22, 2022 3:43:08 AM: Register named type loader (loader=org.rsmod.plugins.api.cache.name.item.ItemNameLoader@4bdf) <- NamedTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:08 AM: Register named type loader (loader=org.rsmod.plugins.api.cache.name.npc.NpcNameLoader@4cad79bc) <- NamedTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:08 AM: Register named type loader (loader=org.rsmod.plugins.api.cache.name.obj.ObjectNameLoader@2c63762b) <- NamedTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:08 AM: Register named type loader (loader=org.rsmod.plugins.api.cache.name.ui.UserInterfaceNameLoader@7a9eccc4) <- NamedTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:08 AM: Register named type loader (loader=org.rsmod.plugins.api.cache.name.vars.VarpNameLoader@78422efb) <- NamedTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:08 AM: Register named type loader (loader=org.rsmod.plugins.api.cache.name.vars.VarbitNameLoader@5f05c8d6) <- NamedTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:08 AM: Register named type loader (loader=org.rsmod.plugins.api.cache.name.cs2.Cs2NameLoader@68e02f33) <- NamedTypeLoaderList::register()
[DEBUG] Apr 22, 2022 3:43:08 AM: Register named type loader (loader=org.rsmod.plugins.api.cache.name.enum.EnumNameLoader@64942607) <- NamedTypeLoaderList::register()
[INFO] Apr 22, 2022 3:43:08 AM: Loaded 0 script names (2 aliases) <- Cs2NameLoader::load()
[INFO] Apr 22, 2022 3:43:08 AM: Loaded 5 varbit type names <- VarbitNameLoader::load()
[INFO] Apr 22, 2022 3:43:08 AM: Loaded 7 varp type names <- VarpNameLoader::load()
[INFO] Apr 22, 2022 3:43:08 AM: Loaded 0 item type names (0 aliases) <- ItemNameLoader::load()
[INFO] Apr 22, 2022 3:43:08 AM: Loaded 0 object type names (0 aliases) <- ObjectNameLoader::load()
[INFO] Apr 22, 2022 3:43:08 AM: Loaded 25 interface type names <- UserInterfaceNameLoader::load()
[INFO] Apr 22, 2022 3:43:08 AM: Loaded 0 npc type names (0 aliases) <- NpcNameLoader::load()
[INFO] Apr 22, 2022 3:43:08 AM: Loaded 34 component type names <- ComponentNameLoader::load()
Exception in thread "main" java.lang.IllegalStateException: Type with name does not exist (name=enum_1129, file=gameframe.ename.yml, path=/home/ubuntu/IdeaProjects/osrs-game-server/game-server/./plugins/resources/content/gameframe/gameframe.ename.yml)
	at org.rsmod.plugins.api.cache.name.enum.EnumNameLoader.loadAliasFile(EnumNameLoader.kt:53)
	at org.rsmod.plugins.api.cache.name.enum.EnumNameLoader.load(EnumNameLoader.kt:29)
	at org.rsmod.ServerKt$loadTypeNames$1$1$job$1.invokeSuspend(Server.kt:150)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Dark98** [comment]
Fixed by running GenerateNames Gradle Task with cache #201.1
